##################   ESP Home
title: ESP Home
icon: mdi:developer-board
cards:

      - type: vertical-stack
        cards:

        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }  
          content: >
              ## Розетки

        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Туалет - Sonoff mini - подсветка зеркала**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.02_sonoff_mini_uptime_custom
            - entity: sensor.02_sonoff_mini_wifi_signal
              name: Сигнал wi-fi
            - entity: sensor.02_sonoff_mini_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.02_sonoff_mini_relay
              name: Питание
              tap_action: toggle
              
        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Туалет - Sonoff mini - Батарея 1**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.sonoff_l1_heater_uptime_custom
            - entity: sensor.sonoff_l1_heater_wifi_signal
              name: Сигнал wi-fi
            - entity: sensor.sonoff_l1_heater_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.sonoff_l1_heater_relay
              name: Питание
              tap_action: toggle
    
      - type: vertical-stack
        cards:

        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }  
          content: >
              ## Энергомониторы

        # - type: custom:stack-in-card
        #   mode: vertical
        #   cards: 
        - type: markdown
          content: >
             **Прачечная - Blitzwolf BW-SHP 2, стиральная машина**
        - type: custom:stack-in-card
          mode: vertical
          cards: 

          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.bwshp2_uptime_custom
            - entity: sensor.bwshp2_wi_fi_signal
              name: Сигнал wi-fi
            - entity: sensor.bwshp2_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.bwshp2_relay
              name: Питание
              tap_action: toggle
            - entity: switch.bwshp2_led_blue
              name: Синий светодиод
              tap_action: toggle
            - entity: switch.bwshp2_led_red
              name: Красный светодиод
              tap_action: toggle
            - entity: sensor.bwshp2_voltage
              name: Напряжение
            - entity: sensor.bwshp2_current
              name: Ток
            - entity: sensor.load_bwshp2
              name: Потребление
              
              
      - type: vertical-stack
        cards:

        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }  
          content: >
              ## BLE Шлюзы
              
        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Кухня, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.kn_esp32_uptime_custom
            - entity: sensor.kn_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.kn_esp32_firmware_version
              name: Прошивка
            - entity: switch.kn_esp32_restart
              name: Перезагрузка
              icon: mdi:reload
              
        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Гостиная, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.gg_esp32_uptime_custom
            - entity: sensor.gg_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.gg_esp32_firmware_version
              name: Прошивка
            - entity: switch.gg_esp32_restart
              name: Перезагрузка
              icon: mdi:reload

        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Детская Д, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.dd_esp32_uptime_custom
            - entity: sensor.dd_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.dd_esp32_firmware_version
              name: Прошивка
            - entity: switch.dd_esp32_restart
              name: Перезагрузка
              icon: mdi:reload
              
        - type: custom:stack-in-card
          mode: vertical
          cards: 
          - type: markdown
            content: >
               **Детская А, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.da_esp32_uptime_custom
            - entity: sensor.da_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.da_esp32_firmware_version
              name: Прошивка
            - entity: switch.da_esp32_restart
              name: Перезагрузка
              icon: mdi:reload