## Светильники прихожая и коридор
- alias: 03_corr_entr
  initial_state: false
  trigger:
## Нажатие на две кнопки одновременно
  - platform: state
    entity_id: sensor.0x00158d00013fc3bc_click
    to: 'both'
  action: 
  - service: script.turn_on
    data_template:
     entity_id: >-
        {%- if states.light.yeelight_03_ceiling.state == 'off' and states('light.0x00158d000420dbab_light')  == 'off' -%}
        script.01_enter_on
        {%- elif states.light.yeelight_03_ceiling.state == 'off' and states('light.0x00158d000420dbab_light')  == 'on' and (as_timestamp (now()) -as_timestamp(states['light.0x00158d000420dbab_light'].last_changed)|int <= 15) -%}
        script.03_corr_on
        {%- elif states.light.yeelight_03_ceiling.state == 'on' and states('light.0x00158d000420dbab_light')  == 'on' -%}
        script.01_enter_off, script.03_corr_off
        {%- elif states.light.yeelight_03_ceiling.state == 'off' and states('light.0x00158d000420dbab_light')  == 'on' and (as_timestamp (now()) -as_timestamp(states['light.0x00158d000420dbab_light'].last_changed)|int > 15) -%}
        script.01_enter_off
        {%- elif states.light.yeelight_03_ceiling.state == 'on' and states('light.0x00158d000420dbab_light')  == 'off' -%}
        script.03_corr_off
        {%- endif -%}  

## Ручное управление светом
- alias: 03_corr_light
  initial_state: false
  trigger:
## Выключатель на входе
  - platform: state
    entity_id: sensor.0x00158d0001718ca8_click
    to: 'left'
## Кнопка в шкафу
  - platform: state
    entity_id: sensor.0x00158d0001f3fefe_click
    to: 'single'
## Квадратная кнопка на кухне
  - platform: state
    entity_id: sensor.0x00158d0001a672ef_click
    to: 'double'
  action: 
  - service: script.turn_on
    data_template:
     entity_id: >-
        {%- if states.light.yeelight_03_ceiling.state == 'off' -%}
        script.03_corr_on
        {%- elif states.light.yeelight_03_ceiling.state == 'on'-%}
        script.03_corr_off
        {%- endif -%}
        
## Датчик вибрации     
- alias: 03_corr_light_on_vibro
  initial_state: false
  trigger:
## Квадратная датчик вибрации
    - platform: state
      entity_id: sensor.0x00158d0002a4f77e_action
      to: 'vibration'
  condition:
    - condition: state
      entity_id: light.yeelight_03_ceiling
      state: 'off'
    - condition: state
      entity_id: binary_sensor.0x00158d00010f8920_occupancy
      state: 'on'
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_03_ceiling
      data_template:
        brightness_pct: 75
        kelvin: 4000
    - delay: 00:00:15
    - service: light.turn_off
      entity_id:
        - light.yeelight_03_ceiling
        
## Автоматическое отключение света       
- alias: 03_corr_light_auto_off
  initial_state: false
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d00010f8920_occupancy
    to: 'off'
  condition:
   - condition: state
     entity_id: light.yeelight_03_ceiling
     state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.yeelight_03_ceiling
        
## Люстра в коридоре - контроль случайного включения
- alias: 03_corr_light_power
  initial_state: false
  trigger:
  - platform: state
    entity_id: light.yeelight_03_ceiling
    to: 'on' 
    for:
        minutes: 3
  condition:
    - condition: state
      entity_id: binary_sensor.0x00158d00010f8920_occupancy
      state: 'off'
  action:
   - service: light.turn_off
     entity_id:
      - light.yeelight_03_ceiling        
        
## Запись последнего движения в коридоре
- alias: 03_motion_time
  initial_state: false
  trigger:
## Движение в коридоре
  - platform: state
    entity_id: binary_sensor.0x00158d00010f8920_occupancy
    to: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00010f8920"
      payload: "{{ states('sensor.time_date')}}"
      retain: true