## Возобновление питания на выключателе холодильника
- alias: 04_kn_power
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.0x00158d0001fa2934_switch
      state: 'off'
    - condition: state
      entity_id: switch.control_mode
      state: 'on'  
  action:
   - service: switch.turn_on
     entity_id: switch.0x00158d0001fa2934_switch
     
## Включение люстры
- alias: 04_kn_ceiling
  initial_state: true
  trigger:
## Выключатель на входе в кухню - правая кнопка
  - platform: state
    entity_id: sensor.0x00158d000282a130_action
    to: 'single_right'
## 6 клавишник на входе
  - platform: state
    entity_id: sensor.0x04cf8cdf3c794209_action
    to: 'button_1_single'
## Подброс кубика
  - platform: state
    entity_id: sensor.0x00158d000101bdc6_action
    to: 'fall'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'  
  action:    
    - service: switch.toggle
      entity_id: switch.04_kn_mainlight 
  
# Автоматическое включение люстры
- alias: 04_kn_ceiling_auto_on
  initial_state: true
  trigger:
# Датчик движения
  - platform: state
    entity_id: binary_sensor.0x00158d0001e16204_occupancy
    to: 'on'
  condition:
   - condition: state
     entity_id: binary_sensor.04_kn_light
     state: 'on'
   - condition: state
     entity_id: switch.control_mode
     state: 'on'  
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-        
         {%- if states("binary_sensor.tod_night") == 'on' -%}
         script.04_kn_ceiling_auto_4
         {%- elif states("binary_sensor.tod_day") == 'on'  -%}
         script.04_kn_ceiling_auto_2
         {%- else -%}
         script.04_kn_ceiling_auto_3
         {% endif %}
         
# Автоматическое выключение люстры 
- alias: 04_kn_ceiling_auto_off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0001e16204_occupancy
    from: 'on'
    to: 'off' 
  condition:
   - condition: state
     entity_id: binary_sensor.04_kn_autolight
     state: 'on'
   - condition: state
     entity_id: switch.control_mode
     state: 'on' 
  action:
    - service: script.turn_on
      entity_id: script.04_kn_ceiling_off

# Включение подсветки  
- alias: 04_kn_led_toggle
  initial_state: true
  trigger:
## Переворот кубика на 90 градусов
  - platform: state
    entity_id: sensor.0x00158d000101bdc6_action
    to: 'flip90'  
## Выключатель на входе в кухню - левая кнопка
  - platform: state
    entity_id: sensor.0x00158d000282a130_click
    to: 'left'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    service: light.toggle
    entity_id: light.aqara_04_strip

## Обнаружение протечки, раковина     
- alias: 04_kitchen_wleak_washstand_on
  initial_state: true
  trigger:       
   platform: state
   entity_id: binary_sensor.0xec1bbdfffe8f1e42_water_leak
   to: 'on'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0400'
      retain: true
  - service: script.turn_on
    entity_id: script.11_warning


## Протечка устранена, раковина          
- alias: 04_kitchen_wleak_washstand_off
  initial_state: true
  trigger:       
   platform: state
   entity_id: binary_sensor.0xec1bbdfffe8f1e42_water_leak
   from: 'on'
   to: 'off'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0401'
      retain: true
  - service: script.turn_on
    entity_id: script.11_all_ok

## Управление телевизором       
- alias: 04_tv_xiaomi
  initial_state: true
  trigger:
## 6 клавишник на входе
  - platform: state
    entity_id: sensor.0x04cf8cdf3c794209_action
    to: 'button_5_single'
## Правая клавиша, выключатель на входе   
  - platform: state
    entity_id: sensor.0x00158d000282a130_click
    to: 'right_double'
## Двойной тап кубиком
  - platform: state
    entity_id: sensor.0x00158d000101bdc6_action
    to: 'tap'  
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    service: script.turn_on
    entity_id: script.xiaomi_tv
    
## Включение Android Box       
- alias: 04_android
  initial_state: true
  trigger:
## 6 клавишник на входе
  - platform: state
    entity_id: sensor.0x04cf8cdf3c794209_action
    to: 'button_6_double'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    service: script.turn_on
    entity_id: script.mini8_android
    
## Датчик вибрации     
- alias: 04_photo_on_vibro
  initial_state: true
  trigger:
## Датчик вибрации
    - platform: state
      entity_id: sensor.0x00158d0002a8ab8b_action
      to: 'vibration'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: mqtt.publish
      data_template:
        topic: "notification/messages"
        payload_template: '0400'
        retain: true
    
## Запись последнего движения в кухне
- alias: 04_kitchen_motion_time
  initial_state: true
  trigger:
## Движение в кухне
  - platform: state
    entity_id: binary_sensor.0x00158d0001e16204_occupancy
    to: 'on'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001e16204"
      payload: "{{ states('sensor.time_date')}}"
      retain: true