- alias: 05_gg_heater
  id: 'Режим обогрева в гостиной'
  initial_state: false
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - binary_sensor.living_heat
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.binary_sensor.living_heat.state == 'on' -%}
          script.living_home
          {%- elif states.binary_sensor.living_heat.state == 'off' -%}
          script.living_away
          {%- endif -%} 

## Включение увлажнителя и очистителя  
- alias: 05_gg_hum_auto
  id: 'Увлажнение в гостиной'
  initial_state: false
  trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - input_number.humidity_level_gg
        - sensor.05_mean_humidity
        - binary_sensor.living_hum
  action:
    service_template: >-
        {% if states.binary_sensor.living_hum.state == 'off' %}
        switch.turn_off
        {% else %}
        switch.turn_on
        {% endif %}
    data_template:
        entity_id: >-
            {% set current = states('input_number.humidity_level_gg') | float %}
            {% set low = (states('input_number.humidity_level_gg') | float) - 5 %}
            {% set medium = (states('input_number.humidity_level_gg') | float) - 10 %}
            {% set high = (states('input_number.humidity_level_gg') | float) - 15 %}
            {% set humidity = states('sensor.05_mean_humidity') | float %}
            {% if humidity < high %} 
            switch.gg_humidifier_mode_high
            {% elif humidity < medium %} 
            switch.gg_humidifier_mode_medium
            {% elif humidity < low %} 
            switch.gg_humidifier_mode_low
            {% else %} 
            switch.gg_humidifier_mode_auto
            {% endif %}