## Возобновление питания на выключателе люстры
- alias: 05_gg_cell_1_power
  initial_state: true
  trigger:       
   - platform: time_pattern
     minutes: '/1'
  condition:
   - condition: template
     value_template: "{{ states('switch.0x00158d00015723f1_switch_right') != 'on' }}"
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
   - service: switch.turn_on
     entity_id: switch.0x00158d00015723f1_switch_right

# Перезагрузка зависшей люстры
- alias: 05_gg_cell_1_reboot
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.yeelight_05_ceiling1
    to: 'unavailable'
    for:
      minutes: 5
  condition:
  - condition: numeric_state
    entity_id: sensor.unavailable_now_light
    below: 5
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/messages"
      payload_template: '0502'
      retain: true
  - service: switch.turn_off
    entity_id: switch.0x00158d00015723f1_switch_right
    
- id: Гостиная, люстра 1
  alias: 05_gg_cell_1_light
  initial_state: true
  trigger:
## Главный выключатель без нуля
    - platform: state
      entity_id: sensor.0x00158d00015723f1_action
      to: 'single_right'
## Пульт ДУ на три кнопки, первая
    - platform: state
      entity_id: sensor.0x60a423fffe942cf2_action
      to: '1_single'
## Выключатель на столе - левая кнопка
    - platform: state
      entity_id: sensor.0x00158d00027c0e2b_action
      to: 'left'
## Выключатель Aqara Opple
    - platform: state
      entity_id: sensor.0x04cf8cdf3c79360a_action
      to: 'button_3_single'
## Переворот кубика на 180 градусов
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'flip180' 
## Выключатель возле комода - правая кнопка
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_action
      to: 'single_right'
## Выключатель на входе в комнату - левая кнопка
    - platform: state
      entity_id: sensor.0x00158d00013fc3bc_action
      to: 'single_left'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling1.state == 'off' -%}
          script.05_gg_650_1_on
          {%- else -%}
          script.05_gg_650_1_off
          {%- endif -%}  

- id: Гостиная, люстра 2
  alias: 05_gg_cell_2_light
  initial_state: true
  trigger:
## Пульт ДУ на три кнопки, вторая
    - platform: state
      entity_id: sensor.0x60a423fffe942cf2_action
      to: '2_single'
## 4 кнопка Aqara Opple
    - platform: state
      entity_id: sensor.0x04cf8cdf3c79360a_action
      to: 'button_4_single'
## Выключатель на столе - правая кнопка
    - platform: state
      entity_id: sensor.0x00158d00027c0e2b_action
      to: 'right'
## Тряска кубика
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'shake' 
## Выключатель возле комода - левая кнопка
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_action
      to: 'single_left'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling2.state == 'off' -%}
          script.05_gg_650_2_on
          {%- else -%}
          script.05_gg_650_2_off
          {%- endif -%}  
          
- id: Гостиная, настольная лампа
  alias: lr_table_lamp
  initial_state: true
  trigger:
## 1 кнопка Aqara Opple
    - platform: state
      entity_id: sensor.0x04cf8cdf3c79360a_action
      to: 'button_1_single'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_table.state == 'off' -%}
          script.lr_table_lamp_on
          {%- else -%}
          script.lr_table_lamp_off
          {%- endif -%}  

- id: Гостиная, полное освещение
  alias: 05_gg_full_light
  initial_state: true
  trigger:
## Подброс кубика
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'fall' 
## Выключатель возле комода - обе кнопки
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_action
      to: 'single_both'
## Выключатель на столе - обе кнопки
    - platform: state
      entity_id: sensor.0x00158d00027c0e2b_action
      to: 'both'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling1.state == 'on' and states.light.yeelight_05_ceiling2.state == 'on' and states.light.yeelight_05_table.state == 'on' -%}
          script.05_gg_650_full_off
          {%- else -%}
          script.05_gg_650_full_on
          {%- endif -%}  

- id: Гостиная, светильники на стене
  alias: 05_gg_wall_light
  initial_state: true
  trigger:
## Пульт ДУ на три кнопки, третья
  - platform: state
    entity_id: sensor.0x60a423fffe942cf2_action
    to: '3_single'
## 2 кнопка Aqara Opple
  - platform: state
    entity_id: sensor.0x04cf8cdf3c79360a_action
    to: 'button_2_single'
## Круглая кнопка в прихожей
  - platform: state
    entity_id: sensor.0x00158d00010b1963_action
    to: 'single'
## Выключатель на столе - левая кнопка х2
  - platform: state
    entity_id: sensor.0x00158d00027c0e2b_action
    to: 'left_double'
## Переворот кубика на 90 градусов
  - platform: state
    entity_id: sensor.0x00158d0001186d82_action
    to: 'flip90' 
## Выключатель на входе в комнату - правая кнопка
  - platform: state
    entity_id: sensor.0x00158d00013fc3bc_action
    to: 'single_right'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
    service: light.toggle
    entity_id: light.aqara_05_wall
    
- id: Гостиная, подсветка для ТВ
  alias: 05_gg_movie_light
  initial_state: true
  trigger:
## 6 кнопка Aqara Opple
  - platform: state
    entity_id: sensor.0x04cf8cdf3c79360a_action
    to: 'button_6_single'
## Выключатель на столе - правая кнопка х2
  - platform: state
    entity_id: sensor.0x00158d00027c0e2b_action
    to: 'right_double'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:    
    - service: switch.toggle
      entity_id: switch.movie_mode

- id: Гостиная, управление ТВ      
  alias: 05_tv_xiaomi55
  initial_state: true
  trigger:
## 5 кнопка Aqara Opple
  - platform: state
    entity_id: sensor.0x04cf8cdf3c79360a_action
    to: 'button_5_single'
## Двойной тап кубиком
  - platform: state
    entity_id: sensor.0x00158d0001186d82_action
    to: 'tap' 
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
    service: switch.toggle
    entity_id: switch.tv_xiaomi_55

## Люстра на балконе
- alias: 05_gg_balkoon_light_toggle
  initial_state: true
  trigger:
# Выключатель на входе на балкон
  - platform: state
    entity_id: sensor.0x00158d00010b5aee_action
    to: 'single' 
  - platform: state
    entity_id: sensor.0x00158d0001b86d2e_action
    to: 'single' 
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
   - service: light.toggle
     entity_id:
      - light.66633530807d3a766432

## Люстра на балконе вкл
- alias: 05_gg_balkoon_light_on
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.lr_balcony_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.66633530807d3a766432
    state: 'off'
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
   - service: light.turn_on
     entity_id:
      - light.66633530807d3a766432
     data_template:
        brightness_pct: 100
        kelvin: 5500

## Люстра на балконе выкл
- alias: 05_gg_balkoon_light_off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d000449b773_occupancy
    to: 'off'
  condition:
  - condition: state
    entity_id: light.66633530807d3a766432
    state: 'on'
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
   - service: light.turn_off
     entity_id:
      - light.66633530807d3a766432

## Люстра на балконе - контроль случайного включения
- alias: 05_gg_balkoon_light_power
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.66633530807d3a766432
    to: 'on' 
    for:
        minutes: 3
  condition:
  - condition: state
    entity_id: binary_sensor.0x00158d000449b773_occupancy
    state: 'off'
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action:
   - service: light.turn_off
     entity_id:
      - light.66633530807d3a766432
      
- id: Гостиная, запись последнего движения
  alias: lr_motion_time
  initial_state: true
  trigger:
## Движение в гостиной
  - platform: state
    entity_id: binary_sensor.0x00158d0005414857_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0005414857"
      payload: "{{ states('sensor.time_date')}}"
      retain: true
      
- id: Гостиная балкон, запись последнего движения
  alias: lr_b_motion_time
  initial_state: true
  trigger:
## Движение на балконе гостиной
  - platform: state
    entity_id: binary_sensor.0x00158d000449b773_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d000449b773"
      payload: "{{ states('sensor.time_date')}}"
      retain: true