## Включение таймера вентиляции
- alias: 06_bathroom_timer_vent_on
  initial_state: false
  trigger:       
   platform: state
   entity_id: switch.0x00158d0001117040_switch_left
   to: 'on'
  action:
  - service: timer.start
    entity_id: timer.bathroom
    
## Выключение таймера вентиляции
- alias: 06_bathroom_timer_vent_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: switch.0x00158d0001117040_switch_left
   to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.bathroom

## Включение вентиляции     
- alias: 06_bathroom_vent_on
  initial_state: false
  trigger:
## Влажность более 70 процентов
   - platform: numeric_state
     entity_id: sensor.0x00158d0001dcd47e_humidity
     above: 70
## Беспроводный выключатель
   - platform: state
     entity_id: sensor.0x00158d000238a140_click
     to: 'right'
  condition:
     - condition: state
       entity_id: switch.0x00158d0001117040_switch_left
       state: 'off'
     - condition: time
       after: '08:00:00'
       before: '22:00:00'
  action:
  - service: timer.start
    entity_id: timer.bathroom
  - service: switch.turn_on
    entity_id: switch.0x00158d0001117040_switch_left

## Выключение вентиляции 
- alias: 06_bathroom_vent_off
  initial_state: false
  trigger:    
## Завершение таймера
   - platform: event
     event_type: timer.finished
     event_data:
       entity_id: timer.bathroom
## Беспроводный выключатель
   - platform: state
     entity_id: sensor.0x00158d000238a140_click
     to: 'right'
  condition:
  - condition: state
    entity_id: switch.0x00158d0001117040_switch_left
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.0x00158d0001117040_switch_left
  - service: timer.cancel
    entity_id: timer.bathroom

## Обнаружение протечки, умывальник
- alias: 06_bathroom_wleak_washstand_on
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.0x00158d0001d72fa2_water_leak
   to: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0600'
      retain: true
  - service: script.turn_on
    entity_id: script.11_warning

## Протечка устранена, умывальник      
- alias: 06_bathroom_wleak_washstand_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.0x00158d0001d72fa2_water_leak
   from: 'on'
   to: 'off'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0601'
      retain: true
  - service: script.turn_on
    entity_id: script.11_all_ok

## Обнаружение протечки, душевая кабина  
- alias: 06_bathroom_wleak_shower_on
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.0x00158d0001bb60c2_water_leak
   to: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0602'
      retain: truee
  - service: script.turn_on
    entity_id: script.11_warning

## Протечка устранена, душевая кабина    
- alias: 06_bathroom_wleak_shower_off
  initial_state: false
  trigger:       
   platform: state
   entity_id: binary_sensor.0x00158d0001bb60c2_water_leak
   from: 'on'
   to: 'off'
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/alarm"
      payload_template: '0603'
      retain: true
  - service: script.turn_on
    entity_id: script.11_all_ok

## Запись последнего движения в ванной
- alias: 06_bathroom_motion_time
  initial_state: false
  trigger:
## Движение в ванной
  - platform: state
    entity_id: binary_sensor.0x00158d0001e547a3_occupancy
    to: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001e547a3"
      payload: "{{ states('sensor.time_date')}}"
      retain: true