- alias: 08_da_heater
  id: 'Режим обогрева детской A'
  initial_state: false
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - binary_sensor.da_heat
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.binary_sensor.da_heat.state == 'on' -%}
          script.da_home
          {%- elif states.binary_sensor.da_heat.state == 'off' -%}
          script.da_away
          {%- endif -%}    


- alias: 08_da_hum_auto
  id: 'Увлажнение в детской А'
  initial_state: false
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - input_number.humidity_level_da
        - sensor.08_mean_humidity
        - binary_sensor.da_hum
  action:
    service_template: >-
      {% set hi = (states('input_number.humidity_level_da') | float) + 5 %}
      {% set lo = (states('input_number.humidity_level_da') | float) - 5 %}
      {% set humidity = states('sensor.08_mean_humidity') | float %}
      {% if humidity > hi %}
        switch.turn_off
      {% elif states.binary_sensor.da_hum.state == 'off' %} 
        switch.turn_off
      {% elif humidity < lo and states.binary_sensor.da_hum.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_{{states('switch.0x00158d00010ec4b8_switch') | lower}}
      {% endif %}
    entity_id: switch.0x00158d00010ec4b8_switch

## Предупреждение о недостатке воды    
- alias: 08_da_hum_water_warning
  initial_state: false
  trigger:
## Падение мощности менее 10 Ватт
   - platform: numeric_state
     entity_id: sensor.load_158d00010ec4b8
     below: 10
     for:
       minutes: 2
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.0x00158d00010ec4b8_switch
       state: 'on'
## Время работы 
     - condition: state
       entity_id: binary_sensor.da_hum
       state: 'on'
  action:
    - service: mqtt.publish
      data_template:
        topic: "notification/messages"
        payload_template: '0800'
        retain: true
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: F0:B4:29:CC:1F:11
        ringtone_id: 10011
        ringtone_vol: 50