- alias: 08_da_heater
  id: 'Режим обогрева детской A'
  initial_state: false
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - binary_sensor.da_heat
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.binary_sensor.da_heat.state == 'on' -%}
          script.da_home
          {%- elif states.binary_sensor.da_heat.state == 'off' -%}
          script.da_away
          {%- endif -%} 