- alias: 911_mqtt_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   to: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: notify.telegram
      data:
        message: "Потеря связи с MQTT сервером - {{ states('sensor.time_date') }} ."

- alias: 911_mqtt_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   from: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: notify.telegram
      data:
        message: "Связь с MQTT сервером восстановлена в - {{ states('sensor.time_date') }} ."
        
- alias: 911_test_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   to: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '041' 

- alias: 911_test_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   from: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '042'