title: Home Assistant - Raspberry Pi 4 B, 2 GB 71 Резервный сервер
views:
  - !include lovelace/01_system.yaml
  - !include lovelace/02_control.yaml
  - !include lovelace/03_map.yaml
  - !include lovelace/04_climate.yaml
  - !include lovelace/05_outdoor.yaml
  - !include lovelace/06_lan.yaml
  - !include lovelace/07_power.yaml
  - !include lovelace/08_hikvision.yaml
  - !include lovelace/09_camera.yaml
  - !include lovelace/19_plan_map.yaml
  - !include lovelace/20_enter.yaml
  - !include lovelace/21_toilet.yaml
  - !include lovelace/22_bathroom.yaml
  - !include lovelace/23_kitchen.yaml
  - !include lovelace/24_living.yaml
  - !include lovelace/25_dd.yaml
  - !include lovelace/26_da.yaml
  - !include lovelace/30_esphome.yaml
  - !include lovelace/31_automation.yaml
  - !include lovelace/32_switchlight.yaml
  - !include lovelace/33_other.yaml
  