title: Home Assistant - Raspberry Pi 4 B, 2 GB 73 Резервный сервер 2
views:
  - !include lovelace/01_system.yaml
  - !include lovelace/02_control.yaml
  - !include lovelace/03_modes.yaml
  - !include lovelace/04_lan.yaml
  - !include lovelace/05_power.yaml
  - !include lovelace/06_hikvision.yaml
  - !include lovelace/07_camera.yaml
  - !include lovelace/08_ectlb.yaml
  - !include lovelace/09_kitchen.yaml
  - !include lovelace/10_living.yaml
  - !include lovelace/11_dd.yaml
  - !include lovelace/12_da.yaml
  - !include lovelace/13_esphome.yaml
  - !include lovelace/14_plan.yaml
  - !include lovelace/15_automation.yaml
  - !include lovelace/16_switchlight.yaml
  - !include lovelace/20_other.yaml
  - !include lovelace/21_webstat.yaml
  